version: "3.8"
services:
  backend:
    image: "bogdandanielioan/library-manager-spring-angular:latest"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
