version: "3.8"
services:
  backend:
    image: "bogdandanielioan/library-manager-spring-angular:16.3.2022.23.14.59"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
