version: "3.8"
services:
  backend:
    image: "bogdandanielioan/library-manager-spring-angular:18.3.2022.13.7.51"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
